import type { LucideProps } from "lucide-react"
import type React from "react"
import {
  Briefcase,
  Code,
  Database,
  Building,
  Globe,
  Server,
  Palette,
  Users,
  Settings,
  Zap,
  Brain,
  MessageSquare,
  ClipboardCheck,
  Bus,
  BedDouble,
  GraduationCap,
  Lightbulb,
  Smartphone,
  Cpu,
  Network,
  Bot,
  FileCode,
  CuboidIcon as Cube,
  Film,
  MessageCircle,
  UserCircle,
  Mail,
  Phone,
  MapPin,
  ChevronRight,
  Heart,
  Wrench,
  Gamepad2,
  Languages,
  Cloud,
} from "lucide-react"

// Icon component map
const iconComponents: Record<string, React.FC<LucideProps>> = {
  Briefcase,
  Code,
  Database,
  Building,
  Globe,
  Server,
  Palette,
  Users,
  Settings,
  Zap,
  Brain,
  MessageSquare,
  ClipboardCheck,
  Bus,
  BedDouble,
  GraduationCap,
  Lightbulb,
  Smartphone,
  Cpu,
  Network,
  Bot,
  FileCode,
  Cube,
  Film,
  MessageCircle,
  UserCircle,
  Mail,
  Phone,
  MapPin,
  ChevronRight,
  Heart,
  Wrench,
  Gamepad2,
  Languages,
  Cloud,
  // Tech specific aliases
  DatabaseZap: Zap,
  React: Code,
  Nextjs: Code,
  NodeJs: Code,
  Python: Code,
  MongoDB: Database,
  MySQL: Database,
  Firebase: Database,
  Supabase: Database,
  TailwindCSS: Palette,
  Cpp: FileCode,
  Android: Smartphone,
  Blender: Cube,
  AfterEffects: Film,
  // Default fallback
  Default: Code,
}

export const GetIcon = ({ name, ...props }: { name: string } & LucideProps) => {
  const IconComponent = iconComponents[name] || iconComponents["Default"]
  return <IconComponent {...props} />
}
